// Generated by gencpp from file localize/Pose.msg
// DO NOT EDIT!


#ifndef LOCALIZE_MESSAGE_POSE_H
#define LOCALIZE_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localize
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : X(0.0)
    , Y(0.0)
    , HeadingAngle(0.0)  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , HeadingAngle(0.0)  {
    }



   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;

   typedef double _HeadingAngle_type;
  _HeadingAngle_type HeadingAngle;




  typedef boost::shared_ptr< ::localize::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localize::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::localize::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::localize::Pose > PosePtr;
typedef boost::shared_ptr< ::localize::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localize::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localize::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localize

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'localize': ['/home/mpc/Localization/workspace/src/localize/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localize::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localize::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localize::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localize::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localize::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localize::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localize::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c26ea479c208023c331628ac9f394de8";
  }

  static const char* value(const ::localize::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc26ea479c208023cULL;
  static const uint64_t static_value2 = 0x331628ac9f394de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::localize::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localize/Pose";
  }

  static const char* value(const ::localize::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localize::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 X\n\
float64 Y\n\
float64 HeadingAngle\n\
\n\
";
  }

  static const char* value(const ::localize::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localize::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.HeadingAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localize::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localize::Pose_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
    s << indent << "HeadingAngle: ";
    Printer<double>::stream(s, indent + "  ", v.HeadingAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZE_MESSAGE_POSE_H
